"""patient menu

Revision ID: eead79cdfa32
Revises: 66e83ec85f10
Create Date: 2023-06-08 19:56:41.127081

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eead79cdfa32'
down_revision = '66e83ec85f10'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
